# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.IntegerField(default=99)),
                ('article_title', models.CharField(max_length=250)),
                ('article_body', models.CharField(max_length=100000)),
                ('article_date', models.CharField(default='December 2017', max_length=100)),
                ('article_link', models.CharField(default='#', max_length=100)),
                ('article_publisher', models.CharField(default='publisher', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_firstmadeas', models.CharField(max_length=20)),
                ('question_popularity', models.PositiveIntegerField(default=1)),
                ('question_abstract', models.IntegerField(default=0)),
                ('question_pubdate', models.DateTimeField(verbose_name='date published')),
                ('question_firstmadeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Article')),
                ('question_firstmadeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_madeat', models.IntegerField(default=1)),
                ('link_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Article')),
                ('link_madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('link_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quizlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_refsentids', models.IntegerField(default=1)),
                ('link_reftexts', models.CharField(max_length=1000)),
                ('link_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Article')),
                ('link_madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('link_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_no', models.PositiveIntegerField(default=1)),
                ('research_keyword', models.CharField(max_length=50)),
                ('research_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_no', models.IntegerField(default=0)),
                ('survey_name', models.CharField(max_length=100)),
                ('survey_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='quizlink',
            name='link_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Research'),
        ),
        migrations.AddField(
            model_name='questionlink',
            name='link_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Research'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Research'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Research'),
        ),
    ]
