# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_rangestart', models.IntegerField(default=0)),
                ('rel_rangeend', models.IntegerField(default=1)),
                ('showat', models.IntegerField(default=1)),
                ('rel_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_popularity',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_abstract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aqrel',
            name='rel_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Question'),
        ),
    ]
