# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0002_auto_20171221_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_cueWord',
        ),
    ]
