# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0004_remove_question_question_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_article',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_madeby',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_popularity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
