# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0009_auto_20180318_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_no', models.PositiveIntegerField(default=1)),
                ('research_keyword', models.CharField(max_length=50)),
                ('research_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_research',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='critReader.Research'),
            preserve_default=False,
        ),
    ]
