# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0010_auto_20180322_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_pubdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 5, 6, 11, 334244, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reftext',
            name='reftext_pubdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 5, 6, 18, 544212, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
