# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0014_remove_reftext_reftext_agreedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_no', models.IntegerField(default=0)),
                ('survey_name', models.CharField(max_length=100)),
                ('survey_link', models.CharField(max_length=200)),
            ],
        ),
    ]
