# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0015_surveyembed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyembed',
            name='survey_link',
            field=models.CharField(max_length=400),
        ),
    ]
