# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.IntegerField(default=99)),
                ('article_title', models.CharField(max_length=250)),
                ('article_body', models.CharField(max_length=100000)),
                ('article_date', models.CharField(default='December 2017', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_importance', models.IntegerField(default=0)),
                ('question_popularity', models.IntegerField(default=0)),
                ('question_cueWord', models.CharField(max_length=100)),
                ('question_refText', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=100)),
                ('question_madeby', models.CharField(max_length=100)),
                ('question_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critReader.Article')),
            ],
        ),
    ]
