# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0008_question_question_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_popularity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
