# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0011_auto_20180322_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
