# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('critReader', '0012_article_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_madeat',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
